import type { Metadata } from "next";
import { db } from "@/app/lib/db";

export const metadata: Metadata = { title: "News — the public record" };

export const dynamic = "force-dynamic";

const TYPE_LABEL: Record<string, string> = {
  candidacy_opened: "Candidacy",
  ballot_opened: "Ballot",
  ballot_result: "Ballot result",
  member_seated: "Seated",
  observer_accepted: "Observer",
  seed_designation: "Seed designation",
  minutes_published: "Minutes",
  framework: "Framework",
  milestone: "Milestone",
};

export default async function NewsPage() {
  const entries = await db.recordEntry.findMany({
    orderBy: { publishedAt: "desc" },
    take: 200,
  });

  return (
    <>
      {/* Hero */}
      <section className="border-b border-rule">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
          <p className="tag mb-4">News</p>
          <h1 className="display text-4xl sm:text-5xl leading-tight max-w-3xl">
            The public record
          </h1>
          <div className="accent-line mt-6" />
          <p className="mt-8 text-lg text-muted max-w-2xl leading-relaxed">
            Candidacies, ballots, seatings, minutes, and milestones —
            generated by the actions themselves, not written editorially.
          </p>
        </div>
      </section>

      <section>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          {entries.length === 0 ? (
            <p className="text-muted text-sm">
              The record opens with the first candidacy.
            </p>
          ) : (
            <ul className="grid gap-5 max-w-3xl">
              {entries.map((e) => (
                <li key={e.id} className="grid sm:grid-cols-[7rem_7rem_1fr] gap-2 sm:gap-4 text-sm border-b border-rule pb-4">
                  <span className="font-mono text-muted">
                    {e.publishedAt.toISOString().slice(0, 10)}
                  </span>
                  <span className="badge self-start">
                    {TYPE_LABEL[e.type] ?? e.type}
                  </span>
                  <span>
                    {e.url ? (
                      <a href={e.url} rel="noopener" className="hover:underline">
                        {e.title} ↗
                      </a>
                    ) : (
                      e.title
                    )}
                    {e.body && (
                      <span className="block text-muted text-xs mt-1 whitespace-pre-line">
                        {e.body}
                      </span>
                    )}
                  </span>
                </li>
              ))}
            </ul>
          )}
        </div>
      </section>
    </>
  );
}
